var annotated_dup =
[
    [ "Storm", "namespace_storm.html", [
      [ "detail_", "namespace_storm_1_1detail__.html", [
        [ "DerivedFromCrtpInterfaceImpl_", "struct_storm_1_1detail___1_1_derived_from_crtp_interface_impl__.html", null ]
      ] ],
      [ "Feathers", null, [
        [ "CubicSecondLimiter", "class_storm_1_1_feathers_1_1_cubic_second_limiter.html", "class_storm_1_1_feathers_1_1_cubic_second_limiter" ],
        [ "CubicSlopeLimiter", "class_storm_1_1_feathers_1_1_cubic_slope_limiter.html", "class_storm_1_1_feathers_1_1_cubic_slope_limiter" ],
        [ "DummySecondLimiter", "class_storm_1_1_feathers_1_1_dummy_second_limiter.html", "class_storm_1_1_feathers_1_1_dummy_second_limiter" ],
        [ "Field", "class_storm_1_1_feathers_1_1_field.html", "class_storm_1_1_feathers_1_1_field" ],
        [ "GradientLimiterScheme", "class_storm_1_1_feathers_1_1_gradient_limiter_scheme.html", "class_storm_1_1_feathers_1_1_gradient_limiter_scheme" ],
        [ "iConvectionScheme", "class_storm_1_1_feathers_1_1i_convection_scheme.html", "class_storm_1_1_feathers_1_1i_convection_scheme" ],
        [ "LaxFriedrichsFluxScheme", "class_storm_1_1_feathers_1_1_lax_friedrichs_flux_scheme.html", null ],
        [ "LaxFriedrichsFluxScheme< tGasPhysics >", "class_storm_1_1_feathers_1_1_lax_friedrichs_flux_scheme_3_01t_gas_physics_01_4.html", "class_storm_1_1_feathers_1_1_lax_friedrichs_flux_scheme_3_01t_gas_physics_01_4" ],
        [ "LeastSquaresGradientScheme", "class_storm_1_1_feathers_1_1_least_squares_gradient_scheme.html", "class_storm_1_1_feathers_1_1_least_squares_gradient_scheme" ],
        [ "LinearUpwindConvectionScheme", "class_storm_1_1_feathers_1_1_linear_upwind_convection_scheme.html", "class_storm_1_1_feathers_1_1_linear_upwind_convection_scheme" ],
        [ "MhdFvBcFarFieldT", "class_storm_1_1_feathers_1_1_mhd_fv_bc_far_field_t.html", null ],
        [ "MhdFvBcNoSlipT", "class_storm_1_1_feathers_1_1_mhd_fv_bc_no_slip_t.html", null ],
        [ "MhdFvBcPT", "class_storm_1_1_feathers_1_1_mhd_fv_bc_p_t.html", "class_storm_1_1_feathers_1_1_mhd_fv_bc_p_t" ],
        [ "MhdFvBcSlipT", "class_storm_1_1_feathers_1_1_mhd_fv_bc_slip_t.html", null ],
        [ "MhdFvSolverT", "class_storm_1_1_feathers_1_1_mhd_fv_solver_t.html", "class_storm_1_1_feathers_1_1_mhd_fv_solver_t" ],
        [ "MhdHydroVars", "class_storm_1_1_feathers_1_1_mhd_hydro_vars.html", "class_storm_1_1_feathers_1_1_mhd_hydro_vars" ],
        [ "MinmodSlopeLimiter", "class_storm_1_1_feathers_1_1_minmod_slope_limiter.html", "class_storm_1_1_feathers_1_1_minmod_slope_limiter" ],
        [ "sFieldDesc", "struct_storm_1_1_feathers_1_1s_field_desc.html", null ],
        [ "tGasPhysics", "class_storm_1_1_feathers_1_1t_gas_physics.html", null ],
        [ "UpwindConvectionScheme", "class_storm_1_1_feathers_1_1_upwind_convection_scheme.html", "class_storm_1_1_feathers_1_1_upwind_convection_scheme" ],
        [ "VenkatakrishnanSlopeLimiter", "class_storm_1_1_feathers_1_1_venkatakrishnan_slope_limiter.html", "class_storm_1_1_feathers_1_1_venkatakrishnan_slope_limiter" ]
      ] ],
      [ "meta", "namespace_storm_1_1meta.html", [
        [ "append_fn", "struct_storm_1_1meta_1_1append__fn.html", null ],
        [ "cartesian_product_fn", "struct_storm_1_1meta_1_1cartesian__product__fn.html", null ],
        [ "concat_fn", "struct_storm_1_1meta_1_1concat__fn.html", null ],
        [ "empty_t", "struct_storm_1_1meta_1_1empty__t.html", null ],
        [ "l_pair_list_fn", "struct_storm_1_1meta_1_1l__pair__list__fn.html", null ],
        [ "list", "struct_storm_1_1meta_1_1list.html", null ],
        [ "list_cast_fn", "struct_storm_1_1meta_1_1list__cast__fn.html", null ],
        [ "pair_cast_fn", "struct_storm_1_1meta_1_1pair__cast__fn.html", null ],
        [ "pair_list", "struct_storm_1_1meta_1_1pair__list.html", null ],
        [ "pair_list< list< Ts... >, X >", "struct_storm_1_1meta_1_1pair__list_3_01list_3_01_ts_8_8_8_01_4_00_01_x_01_4.html", null ],
        [ "pair_list< X, list< Ts... > >", "struct_storm_1_1meta_1_1pair__list_3_01_x_00_01list_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "prepend_fn", "struct_storm_1_1meta_1_1prepend__fn.html", null ],
        [ "query_fn", "struct_storm_1_1meta_1_1query__fn.html", null ],
        [ "r_pair_list_fn", "struct_storm_1_1meta_1_1r__pair__list__fn.html", null ],
        [ "raw", "struct_storm_1_1meta_1_1raw.html", null ],
        [ "raw< type< T > >", "struct_storm_1_1meta_1_1raw_3_01type_3_01_t_01_4_01_4.html", null ],
        [ "reduce_fn", "struct_storm_1_1meta_1_1reduce__fn.html", null ],
        [ "reverse_fn", "struct_storm_1_1meta_1_1reverse__fn.html", null ],
        [ "transform_fn", "struct_storm_1_1meta_1_1transform__fn.html", null ],
        [ "type", "struct_storm_1_1meta_1_1type.html", null ],
        [ "unique_fn", "struct_storm_1_1meta_1_1unique__fn.html", null ]
      ] ],
      [ "shapes", "namespace_storm_1_1shapes.html", [
        [ "Hexahedron", "class_storm_1_1shapes_1_1_hexahedron.html", "class_storm_1_1shapes_1_1_hexahedron" ],
        [ "Pentahedron", "class_storm_1_1shapes_1_1_pentahedron.html", "class_storm_1_1shapes_1_1_pentahedron" ],
        [ "Polygon", "class_storm_1_1shapes_1_1_polygon.html", "class_storm_1_1shapes_1_1_polygon" ],
        [ "Pyramid", "class_storm_1_1shapes_1_1_pyramid.html", "class_storm_1_1shapes_1_1_pyramid" ],
        [ "Quadrangle", "class_storm_1_1shapes_1_1_quadrangle.html", "class_storm_1_1shapes_1_1_quadrangle" ],
        [ "Seg", "class_storm_1_1shapes_1_1_seg.html", "class_storm_1_1shapes_1_1_seg" ],
        [ "Tetrahedron", "class_storm_1_1shapes_1_1_tetrahedron.html", "class_storm_1_1shapes_1_1_tetrahedron" ],
        [ "Triangle", "class_storm_1_1shapes_1_1_triangle.html", "class_storm_1_1shapes_1_1_triangle" ],
        [ "TriangleStrip", "class_storm_1_1shapes_1_1_triangle_strip.html", "class_storm_1_1shapes_1_1_triangle_strip" ]
      ] ],
      [ "Vulture", null, [
        [ "gl", null, [
          [ "BindProgram", "class_storm_1_1_vulture_1_1gl_1_1_bind_program.html", "class_storm_1_1_vulture_1_1gl_1_1_bind_program" ],
          [ "BindWindow", "class_storm_1_1_vulture_1_1gl_1_1_bind_window.html", "class_storm_1_1_vulture_1_1gl_1_1_bind_window" ],
          [ "Buffer", "class_storm_1_1_vulture_1_1gl_1_1_buffer.html", "class_storm_1_1_vulture_1_1gl_1_1_buffer" ],
          [ "DebugOutput", "class_storm_1_1_vulture_1_1gl_1_1_debug_output.html", "class_storm_1_1_vulture_1_1gl_1_1_debug_output" ],
          [ "Framebuffer", "class_storm_1_1_vulture_1_1gl_1_1_framebuffer.html", "class_storm_1_1_vulture_1_1gl_1_1_framebuffer" ],
          [ "Framework", "class_storm_1_1_vulture_1_1gl_1_1_framework.html", "class_storm_1_1_vulture_1_1gl_1_1_framework" ],
          [ "indexed_t", "struct_storm_1_1_vulture_1_1gl_1_1indexed__t.html", null ],
          [ "MultisampledTexture2D", "class_storm_1_1_vulture_1_1gl_1_1_multisampled_texture2_d.html", "class_storm_1_1_vulture_1_1gl_1_1_multisampled_texture2_d" ],
          [ "pixel_desc_t", "struct_storm_1_1_vulture_1_1gl_1_1pixel__desc__t.html", "struct_storm_1_1_vulture_1_1gl_1_1pixel__desc__t" ],
          [ "Program", "class_storm_1_1_vulture_1_1gl_1_1_program.html", "class_storm_1_1_vulture_1_1gl_1_1_program" ],
          [ "Shader", "class_storm_1_1_vulture_1_1gl_1_1_shader.html", "class_storm_1_1_vulture_1_1gl_1_1_shader" ],
          [ "Texture", "class_storm_1_1_vulture_1_1gl_1_1_texture.html", "class_storm_1_1_vulture_1_1gl_1_1_texture" ],
          [ "Texture2D", "class_storm_1_1_vulture_1_1gl_1_1_texture2_d.html", "class_storm_1_1_vulture_1_1gl_1_1_texture2_d" ],
          [ "TextureBuffer", "class_storm_1_1_vulture_1_1gl_1_1_texture_buffer.html", "class_storm_1_1_vulture_1_1gl_1_1_texture_buffer" ],
          [ "VertexArray", "class_storm_1_1_vulture_1_1gl_1_1_vertex_array.html", "class_storm_1_1_vulture_1_1gl_1_1_vertex_array" ],
          [ "Window", "class_storm_1_1_vulture_1_1gl_1_1_window.html", "class_storm_1_1_vulture_1_1gl_1_1_window" ]
        ] ],
        [ "scene", null, [
          [ "Camera", "class_storm_1_1_vulture_1_1scene_1_1_camera.html", "class_storm_1_1_vulture_1_1scene_1_1_camera" ],
          [ "MeshRenderer", "class_storm_1_1_vulture_1_1scene_1_1_mesh_renderer.html", "class_storm_1_1_vulture_1_1scene_1_1_mesh_renderer" ],
          [ "Transform", "class_storm_1_1_vulture_1_1scene_1_1_transform.html", "class_storm_1_1_vulture_1_1scene_1_1_transform" ]
        ] ]
      ] ],
      [ "AABB", "class_storm_1_1_a_a_b_b.html", "class_storm_1_1_a_a_b_b" ],
      [ "Abs", "class_storm_1_1_abs.html", null ],
      [ "AbsSquared", "class_storm_1_1_abs_squared.html", null ],
      [ "Acos", "class_storm_1_1_acos.html", null ],
      [ "Acosh", "class_storm_1_1_acosh.html", null ],
      [ "Add", "class_storm_1_1_add.html", null ],
      [ "AddAssign", "class_storm_1_1_add_assign.html", null ],
      [ "AllIndices", "class_storm_1_1_all_indices.html", null ],
      [ "And", "class_storm_1_1_and.html", null ],
      [ "ApproxEqual", "class_storm_1_1_approx_equal.html", null ],
      [ "Asin", "class_storm_1_1_asin.html", null ],
      [ "Asinh", "class_storm_1_1_asinh.html", null ],
      [ "Assign", "class_storm_1_1_assign.html", null ],
      [ "Atan", "class_storm_1_1_atan.html", null ],
      [ "Atanh", "class_storm_1_1_atanh.html", null ],
      [ "BaseGmresSolver", "class_storm_1_1_base_gmres_solver.html", null ],
      [ "BaseTfqmrSolver", "class_storm_1_1_base_tfqmr_solver.html", null ],
      [ "BiCgStabLSolver", "class_storm_1_1_bi_cg_stab_l_solver.html", null ],
      [ "BiCgStabSolver", "class_storm_1_1_bi_cg_stab_solver.html", null ],
      [ "BindFirst", "class_storm_1_1_bind_first.html", null ],
      [ "BindLast", "class_storm_1_1_bind_last.html", null ],
      [ "Cast", "class_storm_1_1_cast.html", null ],
      [ "Cbrt", "class_storm_1_1_cbrt.html", null ],
      [ "CellView", "class_storm_1_1_cell_view.html", "class_storm_1_1_cell_view" ],
      [ "CgSolver", "class_storm_1_1_cg_solver.html", null ],
      [ "CgsSolver", "class_storm_1_1_cgs_solver.html", null ],
      [ "Compose", "class_storm_1_1_compose.html", null ],
      [ "Compose< Func1, Func2 >", "class_storm_1_1_compose_3_01_func1_00_01_func2_01_4.html", null ],
      [ "Conj", "class_storm_1_1_conj.html", null ],
      [ "Cos", "class_storm_1_1_cos.html", null ],
      [ "Cosh", "class_storm_1_1_cosh.html", null ],
      [ "CrossProductView", "class_storm_1_1_cross_product_view.html", "class_storm_1_1_cross_product_view" ],
      [ "CsrTable", "class_storm_1_1_csr_table.html", "class_storm_1_1_csr_table" ],
      [ "DenseMatrix", "class_storm_1_1_dense_matrix.html", "class_storm_1_1_dense_matrix" ],
      [ "DivideAssign", "class_storm_1_1_divide_assign.html", null ],
      [ "DotProduct", "class_storm_1_1_dot_product.html", null ],
      [ "EdgeView", "class_storm_1_1_edge_view.html", "class_storm_1_1_edge_view" ],
      [ "EntityView", "class_storm_1_1_entity_view.html", "class_storm_1_1_entity_view" ],
      [ "Exp", "class_storm_1_1_exp.html", null ],
      [ "Exp2", "class_storm_1_1_exp2.html", null ],
      [ "FaceView", "class_storm_1_1_face_view.html", "class_storm_1_1_face_view" ],
      [ "FgmresSolver", "class_storm_1_1_fgmres_solver.html", null ],
      [ "FilteringStreambuf", "class_storm_1_1_filtering_streambuf.html", "class_storm_1_1_filtering_streambuf" ],
      [ "FunctionalOperator", "class_storm_1_1_functional_operator.html", "class_storm_1_1_functional_operator" ],
      [ "GmresSolver", "class_storm_1_1_gmres_solver.html", null ],
      [ "IdentityPreconditioner", "class_storm_1_1_identity_preconditioner.html", null ],
      [ "IdrsSolver", "class_storm_1_1_idrs_solver.html", null ],
      [ "Imag", "class_storm_1_1_imag.html", null ],
      [ "Index", "class_storm_1_1_index.html", "class_storm_1_1_index" ],
      [ "IndexedArray", "class_storm_1_1_indexed_array.html", "class_storm_1_1_indexed_array" ],
      [ "IndexedVector", "class_storm_1_1_indexed_vector.html", "class_storm_1_1_indexed_vector" ],
      [ "InnerOuterIterativeSolver", "class_storm_1_1_inner_outer_iterative_solver.html", "class_storm_1_1_inner_outer_iterative_solver" ],
      [ "IterativeSolver", "class_storm_1_1_iterative_solver.html", "class_storm_1_1_iterative_solver" ],
      [ "JfnkSolver", "class_storm_1_1_jfnk_solver.html", null ],
      [ "Log", "class_storm_1_1_log.html", null ],
      [ "Log10", "class_storm_1_1_log10.html", null ],
      [ "Log2", "class_storm_1_1_log2.html", null ],
      [ "MakeMatrixView", "class_storm_1_1_make_matrix_view.html", "class_storm_1_1_make_matrix_view" ],
      [ "MapMatrixView", "class_storm_1_1_map_matrix_view.html", "class_storm_1_1_map_matrix_view" ],
      [ "MatrixOwningView", "class_storm_1_1_matrix_owning_view.html", "class_storm_1_1_matrix_owning_view" ],
      [ "MatrixProductView", "class_storm_1_1_matrix_product_view.html", "class_storm_1_1_matrix_product_view" ],
      [ "MatrixRefView", "class_storm_1_1_matrix_ref_view.html", "class_storm_1_1_matrix_ref_view" ],
      [ "MatrixViewInterface", "class_storm_1_1_matrix_view_interface.html", null ],
      [ "Max", "class_storm_1_1_max.html", null ],
      [ "Merge", "class_storm_1_1_merge.html", null ],
      [ "MeshInterface", "class_storm_1_1_mesh_interface.html", "class_storm_1_1_mesh_interface" ],
      [ "Min", "class_storm_1_1_min.html", null ],
      [ "Multiply", "class_storm_1_1_multiply.html", null ],
      [ "MultiplyAssign", "class_storm_1_1_multiply_assign.html", null ],
      [ "NewtonSolver", "class_storm_1_1_newton_solver.html", null ],
      [ "NodeView", "class_storm_1_1_node_view.html", "class_storm_1_1_node_view" ],
      [ "NonAssignable", "class_storm_1_1_non_assignable.html", "class_storm_1_1_non_assignable" ],
      [ "NonCopyable", "class_storm_1_1_non_copyable.html", "class_storm_1_1_non_copyable" ],
      [ "NonMovable", "class_storm_1_1_non_movable.html", "class_storm_1_1_non_movable" ],
      [ "Object", "class_storm_1_1_object.html", "class_storm_1_1_object" ],
      [ "Operator", "class_storm_1_1_operator.html", "class_storm_1_1_operator" ],
      [ "Or", "class_storm_1_1_or.html", null ],
      [ "Pow", "class_storm_1_1_pow.html", null ],
      [ "Preconditioner", "class_storm_1_1_preconditioner.html", "class_storm_1_1_preconditioner" ],
      [ "Real", "class_storm_1_1_real.html", null ],
      [ "RichardsonSolver", "class_storm_1_1_richardson_solver.html", null ],
      [ "SelectedIndices", "class_storm_1_1_selected_indices.html", null ],
      [ "Sign", "class_storm_1_1_sign.html", null ],
      [ "Sin", "class_storm_1_1_sin.html", null ],
      [ "Sinh", "class_storm_1_1_sinh.html", null ],
      [ "SlicedIndices", "class_storm_1_1_sliced_indices.html", null ],
      [ "Solver", "class_storm_1_1_solver.html", "class_storm_1_1_solver" ],
      [ "Sqrt", "class_storm_1_1_sqrt.html", null ],
      [ "StaticMatrix", "class_storm_1_1_static_matrix.html", "class_storm_1_1_static_matrix" ],
      [ "SubmatrixView", "class_storm_1_1_submatrix_view.html", "class_storm_1_1_submatrix_view" ],
      [ "SubtractAssign", "class_storm_1_1_subtract_assign.html", null ],
      [ "TableInterface", "class_storm_1_1_table_interface.html", "class_storm_1_1_table_interface" ],
      [ "Tan", "class_storm_1_1_tan.html", null ],
      [ "Tanh", "class_storm_1_1_tanh.html", null ],
      [ "TargetMatrixInterface", "class_storm_1_1_target_matrix_interface.html", "class_storm_1_1_target_matrix_interface" ],
      [ "TargetMatrixView", "class_storm_1_1_target_matrix_view.html", "class_storm_1_1_target_matrix_view" ],
      [ "Tfqmr1Solver", "class_storm_1_1_tfqmr1_solver.html", null ],
      [ "TfqmrSolver", "class_storm_1_1_tfqmr_solver.html", null ],
      [ "TopologicalIndexTag", "struct_storm_1_1_topological_index_tag.html", null ],
      [ "TransposeMatrixView", "class_storm_1_1_transpose_matrix_view.html", "class_storm_1_1_transpose_matrix_view" ],
      [ "UnstructuredMesh", "class_storm_1_1_unstructured_mesh.html", "class_storm_1_1_unstructured_mesh" ],
      [ "VovTable", "class_storm_1_1_vov_table.html", "class_storm_1_1_vov_table" ]
    ] ]
];