#!/usr/bin/env python
# -*- coding: utf-8 -*-

import tempfile
import sys
import os
import fypp

temppath = os.path.join(tempfile._get_default_tempdir(),\
                   next(tempfile._get_candidate_names()))

os.system('gfortran ' + ' '.join(sys.argv[1:]))
